module TelegramBot
  class Message
    include JSON::Serializable

    property message_id : Int32
    property message_thread_id : Int32?
    property direct_messages_topic : DirectMessagesTopic?
    property from : User?
    property sender_chat : Chat?
    property sender_boost_count : Int32?
    property sender_business_bot : User?
    property guest_bot_caller_user : User?
    property guest_bot_caller_chat : Chat?
    property guest_query_id : String?
    property date : Int32
    property business_connection_id : String?
    property chat : Chat
    property forward_origin : MessageOrigin?
    property forward_from : User?
    property forward_from_chat : Chat?
    property forward_from_message_id : Int32?
    property forward_signature : String?
    property forward_sender_name : String?
    property forward_date : Int32?
    property? is_topic_message : Bool?
    property? is_automatic_forward : Bool?
    property reply_to_message : Message?
    property external_reply : ExternalReplyInfo?
    property quote : TextQuote?
    property reply_to_story : Story?
    property reply_to_checklist_task_id : Int32?
    property reply_to_poll_option_id : String?
    property via_bot : User?
    property edit_date : Int32?
    property? has_protected_content : Bool?
    property? is_from_offline : Bool?
    property? is_paid_post : Bool?
    property suggested_post_info : SuggestedPostInfo?
    property media_group_id : String?
    property author_signature : String?
    property paid_star_count : Int32?
    property text : String?
    property entities : Array(MessageEntity)?
    property link_preview_options : LinkPreviewOptions?
    property effect_id : String?
    property animation : Animation?
    property audio : Audio?
    property document : Document?
    property live_photo : LivePhoto?
    property paid_media : PaidMediaInfo?
    property photo : Array(PhotoSize)?
    property sticker : Sticker?
    property video : Video?
    property video_note : VideoNote?
    property voice : Voice?
    property caption : String?
    property caption_entities : Array(MessageEntity)?
    property? show_caption_above_media : Bool?
    property? has_media_spoiler : Bool?
    property checklist : Checklist?
    property contact : Contact?
    property dice : Dice?
    property game : Game?
    property poll : Poll?
    property web_app_data : WebAppData?
    property location : Location?
    property venue : Venue?
    property new_chat_members : Array(User)?
    property left_chat_member : User?
    property new_chat_title : String?
    property new_chat_photo : Array(PhotoSize)?
    property? delete_chat_photo : Bool?
    property? group_chat_created : Bool?
    property? supergroup_chat_created : Bool?
    property? channel_chat_created : Bool?
    property forum_topic_created : ForumTopicCreated?
    property forum_topic_edited : ForumTopicEdited?
    property forum_topic_closed : ForumTopicClosed?
    property forum_topic_reopened : ForumTopicReopened?
    property general_forum_topic_hidden : GeneralForumTopicHidden?
    property general_forum_topic_unhidden : GeneralForumTopicUnhidden?
    property poll_option_added : PollOptionAdded?
    property poll_option_deleted : PollOptionDeleted?
    property migrate_to_chat_id : Int32?
    property migrate_from_chat_id : Int32?
    property pinned_message : Message?
    property invoice : Invoice?
    property successful_payment : SuccessfulPayment?
    property refunded_payment : RefundedPayment?
    property gift : GiftInfo?
    property unique_gift : UniqueGiftInfo?
    property gift_upgrade_sent : GiftInfo?
    property checklist_tasks_done : ChecklistTasksDone?
    property checklist_tasks_added : ChecklistTasksAdded?
    property managed_bot_created : ManagedBotCreated?
    property suggested_post_approved : SuggestedPostApproved?
    property suggested_post_approval_failed : SuggestedPostApprovalFailed?
    property suggested_post_declined : SuggestedPostDeclined?
    property suggested_post_paid : SuggestedPostPaid?
    property suggested_post_refunded : SuggestedPostRefunded?
    property reply_markup : InlineKeyboardMarkup?
  end
end
